# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_DecisionTree.ipynb.

# %% auto 0
__all__ = ['fig', 'ax', 'scatter', 'cbar']

# %% ../nbs/02_DecisionTree.ipynb 15
import matplotlib.pyplot as plt
import numpy as np

# %% ../nbs/02_DecisionTree.ipynb 18
# Create a 3D scatter plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.set_xlabel('degree_n')
ax.set_ylabel('job_n')
ax.set_zlabel('company_n')

scatter = ax.scatter(inputs_n['degree_n'],
           inputs_n['job_n'],
           inputs_n['company_n'],
           c=target,
           cmap='viridis',
           marker='+')

# Adding a color bar to show the mapping of colors to values in 'color_column'
cbar = fig.colorbar(scatter, ax=ax)
cbar.set_label('Color Column')
