# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_LogisticRegression.ipynb.

# %% auto 0
__all__ = ['report']

# %% ../nbs/04_LogisticRegression.ipynb 35
from sklearn.metrics import classification_report

# %% ../nbs/04_LogisticRegression.ipynb 36
report = classification_report(y_test, y_predicted)
print(report)
