# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ML',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/ML',
                'lib_path': 'MLexamples'},
  'syms': {}}
